### ISSUE TITLE
Experiment: test notification for android

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core-demo#13]
We want to test the Android notification for new app messages.
<img width="247" alt="image" src="https://user-images.githubusercontent.com/5744708/236597849-b34088a8-8e35-402e-99b5-cf309592e7d1.png">

https://www.figma.com/file/HCoiw3jQvKt4vF3P1bZQMp/Wallet?type=whiteboard&node-id=134-955&t=wlzqNkuqJqofvewz-4

**Comment by dagmawig** [comment]
I will work on this

**Comment by dadiorchen** [comment]
@dagmawig thank you!
