### ISSUE TITLE
Create Login Screen in Expo React Native

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-web-map-core-demo#21]
Hello contributors/team,

Your focus will be on creating a visually appealing login screen.
Below are the details of the task:

- Profile , text,  inputs and button to match the [design](https://www.figma.com/file/b9ysoeaLAFcjy2Dlrbu5Ya/Web-Map-Demo?type=design&node-id=429-2925&mode=design&t=hUHsIkIUmesFdD1u-0)

UI Design: 
<img width="215" alt="Screen Shot 2023-07-29 at 6 59 16 PM" src="https://github.com/Greenstand/treetracker-web-map-core-demo/assets/23443242/24eba69f-b696-4bb9-a230-9386b76da505">

Feel free to reach out if you have any questions or need further clarification.

**Comment by dadiorchen** [comment]
Is the `paper` the component lib we are using? @pierrelstan ?

**Comment by pierrelstan** [comment]
Yes , the react native paper is the component library we are using.
