### ISSUE TITLE
Implement Profile Screen 

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-web-map-core-demo#23]
Hello contributors/team,

Your focus will be on creating a visually appealing Profile Screen.

Text, Icons, Profile to match the [design](https://www.figma.com/file/b9ysoeaLAFcjy2Dlrbu5Ya/Web-Map-Demo?type=design&node-id=429-2925&mode=design&t=hUHsIkIUmesFdD1u-0).
UI Design:
<img width="218" alt="Screen Shot 2023-07-29 at 7 16 02 PM" src="https://github.com/Greenstand/treetracker-web-map-core-demo/assets/23443242/2aa46345-aeee-40c4-9ea6-3393b9a89ba8">

Feel free to reach out if you have any questions or need further clarification.

**Comment by dagmawig** [comment]
I will work on this

**Comment by dadiorchen** [comment]
Nice

**Comment by dadiorchen** [comment]
@dagmawig what's the progress on this?

**Comment by dagmawig** [comment]
@pierrelstan  and I had to figure out how to implement the page as a drawer component. We have an idea now. I should have it complete this week.
