### ISSUE TITLE
Implement transfer Screen

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-web-map-core-demo#24]
Hello contributors/team,

Your focus will be on creating a visually appealing Transfer Screen.

Text, Icons, images input  and button to match the [design](https://www.figma.com/file/b9ysoeaLAFcjy2Dlrbu5Ya/Web-Map-Demo?type=design&node-id=429-2925&mode=design&t=hUHsIkIUmesFdD1u-0).
UI Design:
<img width="216" alt="Screen Shot 2023-07-29 at 7 21 50 PM" src="https://github.com/Greenstand/treetracker-web-map-core-demo/assets/23443242/2b7891bf-8e18-46b1-a977-8d6c840f988a">

Feel free to reach out if you have any questions or need further clarification.

**Comment by sebastiangaertner** [comment]
This looks great. We had a similar wallet app design made a couple years back and i am trying to find the design files for reference.

**Comment by dadiorchen** [comment]
@sebastiangaertner this is a totally demo app, not wallet app, we just use this to prove:
* Web map integration
* It is possible to use React Native to build a good app
* We can build a app for both web version for browser and mobile app in a single codebase and reuse the code as much as possible.

**Comment by dagmawig** [comment]
Is anyone working on this?

**Comment by pierrelstan** [comment]
@dagmawig you can work on it
