### ISSUE TITLE
 Icon Not Displaying

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-web-map-core-demo#41]
Icon is not displaying as expected.

 **Error Occurrence:**
<img width="326" alt="Screen Shot 2023-09-23 at 7 30 40 PM" src="https://github.com/Greenstand/treetracker-web-map-core-demo/assets/23443242/9a90fd28-2400-45af-8035-6208b052a3db">

**Expected Behavior:**
<img width="430" alt="Screen Shot 2023-09-26 at 12 04 23 PM" src="https://github.com/Greenstand/treetracker-web-map-core-demo/assets/23443242/aacf6a18-1ad4-424e-9693-99604d38bccf">

**Comment by dagmawig** [comment]
I can look at this.
